# Generated by Django 5.0.4 on 2024-12-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptac_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('project_category', models.CharField(max_length=100)),
                ('project_title', models.TextField()),
                ('abstract_file', models.FileField(blank=True, null=True, upload_to='abstracts/')),
            ],
        ),
    ]
