# Generated by Django 5.0.4 on 2024-12-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_mark', models.IntegerField()),
                ('final_mark', models.IntegerField()),
                ('plagiarism', models.IntegerField()),
                ('work_log', models.IntegerField()),
                ('total_mark', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.student')),
            ],
        ),
    ]
