# Generated by Django 5.0.4 on 2025-01-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_adminmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ptac_id',
            field=models.CharField(max_length=20),
        ),
    ]
