# Generated by Django 5.0.4 on 2025-01-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_alter_student_ptac_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFeedbackMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.IntegerField()),
                ('novelty', models.IntegerField()),
                ('plagiarism', models.IntegerField()),
                ('originality', models.IntegerField()),
                ('innovation', models.IntegerField()),
                ('qna', models.IntegerField()),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.student')),
            ],
        ),
    ]
