# Generated by Django 5.0.4 on 2025-01-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_teamfeedbackmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmark',
            name='total_mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReviewerMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_objectives', models.IntegerField()),
                ('originality_novelty', models.IntegerField()),
                ('technical_complexity', models.IntegerField()),
                ('ethical_standards', models.IntegerField()),
                ('problem_effectiveness', models.IntegerField()),
                ('team_collaboration', models.IntegerField()),
                ('innovation_creativity', models.IntegerField()),
                ('impact_scalability', models.IntegerField()),
                ('technology_usage', models.IntegerField()),
                ('qna_quality', models.IntegerField()),
                ('total_mark', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.student')),
            ],
        ),
    ]
