# Generated by Django 5.0.4 on 2025-01-04 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_alter_adminmark_total_mark_reviewermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewermark',
            name='mark_provided_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reviewermark',
            name='reviewer_name',
            field=models.CharField(default='default_reviewer', max_length=255),
        ),
    ]
