# Generated by Django 5.0.4 on 2025-02-13 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_reviewermark_mark_provided_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmark',
            name='final_mark',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='adminmark',
            name='initial_mark',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='adminmark',
            name='plagiarism',
            field=models.IntegerField(choices=[(5, '5'), (3, '3'), (0, '0')], default=5),
        ),
        migrations.AlterField(
            model_name='adminmark',
            name='work_log',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (8, '8'), (10, '10')], default=2),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='ethical_standards',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='explanation_objectives',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='impact_scalability',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='innovation_creativity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='originality_novelty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='problem_effectiveness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='qna_quality',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='reviewer_name',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='team_collaboration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='technical_complexity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='reviewermark',
            name='technology_usage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='teamfeedbackmark',
            name='explanation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teamfeedbackmark',
            name='innovation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teamfeedbackmark',
            name='novelty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teamfeedbackmark',
            name='originality',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teamfeedbackmark',
            name='plagiarism',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='teamfeedbackmark',
            name='qna',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
